services:
  flink-jobmanager:
    build:
      context: flink
    command: jobmanager
    ports:
      - "8081:8081"
    depends_on:
      lakehouse-warehouse-init:
        condition: service_completed_successfully
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
    volumes:
      - lakehouse-warehouse:/lakehouse/warehouse

  flink-taskmanager:
    build:
      context: flink
    command: taskmanager
    depends_on:
      - flink-jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - lakehouse-warehouse:/lakehouse/warehouse

volumes:
  lakehouse-warehouse:
