connector.name=iceberg
iceberg.catalog.type=jdbc
iceberg.jdbc-catalog.catalog-name=${ENV:ICEBERG_CATALOG_NAME}
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
iceberg.jdbc-catalog.connection-url=${ENV:ICEBERG_CATALOG_URI}
iceberg.jdbc-catalog.connection-user=${ENV:ICEBERG_CATALOG_USER}
iceberg.jdbc-catalog.connection-password=${ENV:ICEBERG_CATALOG_PASSWORD}
iceberg.jdbc-catalog.default-warehouse-dir=${ENV:ICEBERG_WAREHOUSE}
fs.hadoop.enabled=true
